apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: codis-ha-PRODUCT_NAME
spec:
  replicas: 1
  serviceName: codis-ha-PRODUCT_NAME
  template:
    metadata:
      labels:
        app: codis-ha-PRODUCT_NAME
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["codis-ha-PRODUCT_NAME"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      imagePullSecrets:
      - name: adhoc-docker-registry
      containers:
      - name: codis-ha
        image: registry.appadhoc.com:30443/adhoc-cache:3.2
        imagePullPolicy: IfNotPresent
        command: ["codis-ha"]
        args: ["-l","/tmp/$(POD_NAME).log","--interval","5","--dashboard=$(DASHBOARD_ADDR)"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DASHBOARD_ADDR
          value: "codis-dashboard-PRODUCT_NAME:18080"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
