apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-dashboard-PRODUCT_NAME
  name: codis-dashboard-PRODUCT_NAME
spec:
  clusterIP: None
  ports:
    - port: 18080
  selector:
    app: codis-dashboard-PRODUCT_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-fe-PRODUCT_NAME
  name: codis-fe-PRODUCT_NAME
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31080
  selector:
    app: codis-fe-PRODUCT_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-proxy-PRODUCT_NAME
  name: codis-proxy-PRODUCT_NAME
spec:
  ports:
    - port: 11080
      name: proxy
    - port: 6379
      targetPort: 19000
      name: admin
  selector:
    app: codis-proxy-PRODUCT_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-server-PRODUCT_NAME
  name: codis-server-PRODUCT_NAME
spec:
  clusterIP: None
  ports:
    - port: 6379
  selector:
    app: codis-server-PRODUCT_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codis-ha-PRODUCT_NAME
  name: codis-ha-PRODUCT_NAME
spec:
  clusterIP: None
  ports:
    - port: 12345
  selector:
    app: codis-ha-PRODUCT_NAME