apiVersion: v1
kind: PersistentVolume
metadata:
  name: codis-pv-PRODUCT_NAME-NUM
  labels:
    type: codis-pv-PRODUCT_NAME-NUM
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-vol-default
spec:
  capacity:
    storage: STORAGE
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/codis-pv-PRODUCT_NAME-NUM"
