apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-codis-server-PRODUCT_NAME-NUM
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-vol-default
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: gluster-vol-default
  resources:
    requests:
      storage: STORAGE
  selector:
    matchLabels:
      type: codis-pv-PRODUCT_NAME-NUM